### ISSUE TITLE
Create Get Users routes

### ISSUE THREAD

**Issue by Khaled6120** [AsliSema/byte-and-bite#38]
- Define GET /api/users (Admin) route

**Comment by nourkrimesh** [comment]
![Screenshot 2023-07-17 at 7 16 11 PM](https://github.com/AsliSema/byte-and-bite/assets/22308223/fccbfa71-ad29-4e05-af4a-d6c6f1d70e3e)
not authorized if the user is not an admin

**Comment by nourkrimesh** [comment]
![Screenshot 2023-07-17 at 7 17 38 PM](https://github.com/AsliSema/byte-and-bite/assets/22308223/0cdad0ff-a0a7-456d-a4d4-415db31c8bc5)
authorized admin page 1

**Comment by nourkrimesh** [comment]
![Screenshot 2023-07-17 at 7 18 03 PM](https://github.com/AsliSema/byte-and-bite/assets/22308223/c01bfc25-dfaa-4732-bcac-d8077b984116)
authorized admin page 2

**Comment by nourkrimesh** [comment]
- get all users with pagination. (Done).
- not allowed if the user is not an admin (Done).
