### ISSUE TITLE
Database Architecture Design

### ISSUE THREAD

**Issue by AsliSema** [AsliSema/byte-and-bite#4]
Database architecture design should be completed on Figma.

**Comment by Khaled6120** [comment]
Based on team discussions, the database architecture design has been revised and improved ✅✅

[**Figma Link** ](https://www.figma.com/file/2LFORVZMP6cjBH9JvXeVML/DB-Schema-Design?type=design&node-id=0-1&mode=design&t=rErtLubPHVY8Novy-0)


![image](https://github.com/AsliSema/byte-and-bite/assets/86200305/b671d71a-9eba-4f9c-8d1f-cf9b7cd7fb0b)
