### ISSUE TITLE
System Structure Design 2

### ISSUE THREAD

**Issue by AsliSema** [AsliSema/byte-and-bite#6]
System structure design under the project section should be completed on Figma.

**Comment by baraah-berra** [comment]
![image](https://github.com/AsliSema/byte-and-bite/assets/126883338/d8876891-a6c4-4023-9aef-3ff8af328604)
https://www.figma.com/file/MrXH16NsjHrchEP3Bct6PK/Architecture-Diagram?type=whiteboard&node-id=0-1&t=I2EesXlSReRKIBxV-0
